name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      #      - name: Build with Gradle
      #        run: ./gradlew build -x dokkaHtml -x dokkaHtmlJar
      - uses: burrunan/gradle-cache-action@v1
        name: Build scenery
        with:
          arguments: build -x dokkaHtml -x dokkaHtmlJar -x javadoc -x dokkaJavadocJar
  #      - name: Cleanup Gradle Cache
  #        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
  #        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
  #        run: |
  #          rm -f ~/.gradle/caches/modules-2/modules-2.lock
  #          rm -f ~/.gradle/caches/modules-2/gc.properties

  windows:
    name: 'Windows'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      #      - name: Build with Gradle
      #        run: .\gradlew.bat build -x dokkaHtml -x dokkaHtmlJar
      - uses: burrunan/gradle-cache-action@v1
        name: Build scenery
        with:
          arguments: build -x dokkaHtml -x dokkaHtmlJar -x javadoc -x dokkaJavadocJar
  #      - name: Cleanup Gradle Cache
  #        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
  #        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
  #        run: |
  #          rm -f ~/.gradle/caches/modules-2/modules-2.lock
  #          rm -f ~/.gradle/caches/modules-2/gc.properties

  mac:
    name: 'Mac OS'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      #      - name: Build with Gradle
      #        run: ./gradlew build -x dokkaHtml -x dokkaHtmlJar
      - uses: burrunan/gradle-cache-action@v1
        name: Build scenery
        with:
          arguments: build -x dokkaHtml -x dokkaHtmlJar -x javadoc -x dokkaJavadocJar
#      - name: Cleanup Gradle Cache
#        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
#        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
#        run: |
#          rm -f ~/.gradle/caches/modules-2/modules-2.lock
#          rm -f ~/.gradle/caches/modules-2/gc.properties
